"""Generate a PDF payslip with fpdf2 (pure-Python, no native deps).

Amounts use the hotel's currency CODE (e.g. 'GBP', 'INR') rather than a symbol,
because core PDF fonts are latin-1 only (₹ would fail).
"""
from fpdf import FPDF
from fpdf.enums import XPos, YPos


def generate_payslip(payroll, employee, hotel) -> bytes:
    cur = hotel.base_currency
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, text=hotel.name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, text=f"Payslip - {payroll.pay_period}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, text=employee.full_name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(
        0, 6,
        text=f"Employee: {employee.employee_code}   Role: {employee.job_title or '-'}",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    if employee.ni_number:
        pdf.cell(0, 6, text=f"NI Number: {employee.ni_number}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(
        0, 6,
        text=f"Days present: {payroll.days_present}   Hours: {payroll.total_hours}",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    pdf.ln(4)

    def row(label: str, value: str, *, bold: bool = False) -> None:
        pdf.set_font("Helvetica", "B" if bold else "", 11)
        border = "T" if bold else 0
        pdf.cell(120, 8, text=label, border=border)
        pdf.cell(0, 8, text=value, align="R", border=border, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    row("Gross pay", f"{cur} {payroll.gross_pay}")
    row("Overtime", f"{cur} {payroll.overtime_pay}")
    row("Advance deduction", f"- {cur} {payroll.advance_deduction}")
    row("Other deductions", f"- {cur} {payroll.other_deductions}")
    row("NET PAY", f"{cur} {payroll.net_pay}", bold=True)

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        text=f"Status: {payroll.status}  -  Generated by Mise",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    return bytes(pdf.output())
