"""Branded PDF payslip via fpdf2 (currency code, latin-1 safe)."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos

BRAND = (16, 185, 129)  # emerald
DARK = (15, 23, 42)  # slate-900
MUTED = (100, 116, 139)  # slate-500
LIGHT = (241, 245, 249)  # slate-100


def _s(value) -> str:
    """Make text safe for the built-in latin-1 PDF font (avoids 500s on stray
    unicode like em-dashes or non-latin names). TODO: embed a Unicode TTF."""
    return str(value).encode("latin-1", "replace").decode("latin-1")


def _draw(pdf: FPDF, payroll, employee, hotel) -> None:
    """Render ONE payslip page onto `pdf` (reused for single + consolidated)."""
    cur = hotel.base_currency
    pdf.add_page()

    # ── header band ──
    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 9)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_s(hotel.name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, text=f"PAYSLIP   |   {payroll.pay_period}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── employee block ──
    pdf.set_text_color(*DARK)
    pdf.set_xy(14, 40)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, text=_s(employee.full_name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_text_color(*MUTED)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(
        0, 6,
        text=_s(f"{employee.employee_code}   |   {employee.job_title or 'Staff'}"),
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    pdf.set_x(14)
    meta = f"Days present: {payroll.days_present}    Hours: {payroll.total_hours}"
    if employee.ni_number:
        meta += f"    NI: {employee.ni_number}"
    pdf.cell(0, 6, text=_s(meta), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── earnings / deductions table ──
    pdf.ln(6)

    def line(label: str, value: str, *, shade: bool = False, net: bool = False) -> None:
        pdf.set_x(14)
        if net:
            pdf.set_fill_color(*BRAND)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font("Helvetica", "B", 12)
            fill = True
        else:
            pdf.set_fill_color(*LIGHT)
            pdf.set_text_color(*DARK)
            pdf.set_font("Helvetica", "", 11)
            fill = shade
        pdf.cell(122, 9, text=f"  {label}", border=0, fill=fill)
        pdf.cell(
            60, 9, text=f"{value}  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    line("Gross pay", f"{cur} {payroll.gross_pay}", shade=True)
    line("Overtime", f"{cur} {payroll.overtime_pay}")
    line("Advance deduction", f"- {cur} {payroll.advance_deduction}", shade=True)
    line("Other deductions", f"- {cur} {payroll.other_deductions}")
    pdf.ln(2)
    line("NET PAY", f"{cur} {payroll.net_pay}", net=True)

    # ── footer ──
    pdf.set_text_color(*MUTED)
    pdf.set_xy(14, 280)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5,
        text=f"Status: {payroll.status}   |   Generated by Mise - restaurant intelligence",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )


def generate_payslip(payroll, employee, hotel) -> bytes:
    """A single employee's payslip PDF."""
    pdf = FPDF()
    _draw(pdf, payroll, employee, hotel)
    return bytes(pdf.output())


def generate_consolidated(items, hotel) -> bytes:
    """One PDF containing every payslip for a period — the super-admin's run summary.
    `items` is a list of (payroll, employee) pairs."""
    pdf = FPDF()
    for payroll, employee in items:
        _draw(pdf, payroll, employee, hotel)
    if not items:
        pdf.add_page()
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, text="No payroll for this period.")
    return bytes(pdf.output())
