"""Branded daily sales & cash sheet PDF (currency code, latin-1 safe)."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.core.pdf import money

BRAND = (16, 185, 129)
DARK = (15, 23, 42)
MUTED = (100, 116, 139)
LIGHT = (241, 245, 249)


def _s(value) -> str:
    return str(value).encode("latin-1", "replace").decode("latin-1")


def generate_day_pdf(summary: dict, hotel) -> bytes:
    cur = hotel.base_currency
    t = summary["totals"]
    pdf = FPDF()
    pdf.add_page()

    # header band
    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 9)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_s(hotel.name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0, 6, text=f"DAILY SALES & CASH   |   {summary['date']}",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    # sales-by-channel table
    pdf.set_xy(14, 40)
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(64, 9, text="  Channel", fill=True)
    pdf.cell(28, 9, text="Method", align="C", fill=True)
    pdf.cell(30, 9, text="Gross", align="R", fill=True)
    pdf.cell(30, 9, text="Commission", align="R", fill=True)
    pdf.cell(30, 9, text="Net  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "", 10)
    lines = summary["lines"]
    if not lines:
        pdf.set_x(14)
        pdf.cell(
            0, 9, text="  No sales recorded for this day.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
    for i, ln in enumerate(lines):
        pdf.set_x(14)
        fill = i % 2 == 1
        pdf.set_fill_color(*LIGHT)
        pdf.cell(64, 8, text=_s(f"  {ln['channel_name']}"), fill=fill)
        pdf.cell(28, 8, text=str(ln["payment_method"]), align="C", fill=fill)
        pdf.cell(30, 8, text=money(ln["gross_amount"], cur), align="R", fill=fill)
        pdf.cell(30, 8, text=money(ln["commission"], cur), align="R", fill=fill)
        pdf.cell(
            30, 8, text=money(ln["net_amount"], cur) + "  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    # totals bar
    pdf.set_x(14)
    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(92, 10, text="  Totals", fill=True)
    pdf.cell(30, 10, text=money(t["gross"], cur), align="R", fill=True)
    pdf.cell(30, 10, text=money(t["commission"], cur), align="R", fill=True)
    pdf.cell(
        30, 10, text=money(t["net"], cur) + "  ", align="R", fill=True,
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    # cash reconciliation block
    pdf.ln(8)
    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_x(14)
    pdf.cell(0, 8, text="Cash drawer", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    counted = summary["cash_counted"]
    variance = summary["cash_variance"]
    rec = [
        ("Opening float", money(summary["opening_cash"], cur)),
        ("Cash sales", money(t["cash_sales"], cur)),
        ("Expected in drawer", money(summary["expected_cash"], cur)),
        ("Counted", money(counted, cur) if counted is not None else "not counted"),
        ("Variance", money(variance, cur) if variance is not None else "-"),
    ]
    short = variance is not None and float(variance) != 0
    for label, value in rec:
        pdf.set_x(14)
        bold = label in ("Expected in drawer", "Variance")
        pdf.set_font("Helvetica", "B" if bold else "", 11)
        # Cash missing from the drawer is the one line on this page anyone ever
        # chases, and it was set in the same black as the opening float.
        if label == "Variance" and short:
            pdf.set_text_color(190, 40, 40)
        pdf.cell(92, 8, text=f"  {label}")
        pdf.cell(60, 8, text=f"{value}  ", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*DARK)

    # Writing at y=280 on an A4 page sits below fpdf's bottom margin, so it
    # started a fresh sheet to hold the footer — the blank last page the rota
    # and every shared-helper export had.
    pdf.set_auto_page_break(False)
    pdf.set_text_color(*MUTED)
    pdf.set_xy(14, 280)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5, text="Generated by DineAI - restaurant intelligence",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    return bytes(pdf.output())
