"""Purchase-order PDF via fpdf2 (currency code, latin-1 safe)."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos


def generate_po_pdf(po, vendor_name: str, items: list[dict], hotel) -> bytes:
    cur = hotel.base_currency
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, text=hotel.name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, text=f"Purchase Order: {po.po_number}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, text=f"Vendor: {vendor_name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(86, 8, text="Item", border="B")
    pdf.cell(28, 8, text="Qty", border="B", align="R")
    pdf.cell(34, 8, text="Unit price", border="B", align="R")
    pdf.cell(0, 8, text="Line total", border="B", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    for it in items:
        pdf.cell(86, 7, text=str(it["item_name"]))
        pdf.cell(28, 7, text=str(it["ordered_qty"]), align="R")
        pdf.cell(34, 7, text=f"{cur} {it['unit_price']}", align="R")
        pdf.cell(
            0, 7, text=f"{cur} {it['line_total']}", align="R",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(148, 9, text="Total", border="T")
    pdf.cell(
        0, 9, text=f"{cur} {po.total_amount}", align="R", border="T",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, text="Generated by Mise", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    return bytes(pdf.output())
