"""Branded purchase-order PDF via fpdf2 (currency code, latin-1 safe)."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos

BRAND = (16, 185, 129)
DARK = (15, 23, 42)
MUTED = (100, 116, 139)
LIGHT = (241, 245, 249)


def _s(value) -> str:
    """latin-1-safe text for the built-in PDF font."""
    return str(value).encode("latin-1", "replace").decode("latin-1")


def generate_po_pdf(po, vendor_name: str, items: list[dict], hotel) -> bytes:
    cur = hotel.base_currency
    pdf = FPDF()
    pdf.add_page()

    # header band
    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 9)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_s(hotel.name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, text=f"PURCHASE ORDER   |   {po.po_number}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # vendor block
    pdf.set_text_color(*DARK)
    pdf.set_xy(14, 40)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, text=_s(f"To: {vendor_name}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # table header
    pdf.set_x(14)
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(86, 9, text="  Item", fill=True)
    pdf.cell(28, 9, text="Qty", align="R", fill=True)
    pdf.cell(34, 9, text="Unit price", align="R", fill=True)
    pdf.cell(34, 9, text="Line total  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "", 10)
    for i, it in enumerate(items):
        pdf.set_x(14)
        fill = i % 2 == 1
        pdf.set_fill_color(*LIGHT)
        pdf.cell(86, 8, text=_s(f"  {it['item_name']}"), fill=fill)
        pdf.cell(28, 8, text=str(it["ordered_qty"]), align="R", fill=fill)
        pdf.cell(34, 8, text=f"{cur} {it['unit_price']}", align="R", fill=fill)
        pdf.cell(
            34, 8, text=f"{cur} {it['line_total']}  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    pdf.set_x(14)
    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(148, 10, text="  Total", fill=True)
    pdf.cell(
        34, 10, text=f"{cur} {po.total_amount}  ", align="R", fill=True,
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    pdf.set_text_color(*MUTED)
    pdf.set_xy(14, 280)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5, text="Generated by Mise - restaurant intelligence",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    return bytes(pdf.output())
