"""Excel export + import for the weekly rota.

Export: the week's shifts as a styled workbook. Template: an empty sheet with the
right headers + an example + the valid employee names. Import: parse a filled
template back into shift dicts (best-effort; never raises on bad cells)."""
import io
from datetime import date as date_type
from datetime import datetime, time
from decimal import Decimal

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font

from app.core.xlsx_style import style_table, total_row

# Mise emerald brand for the PDF (RGB).
_BRAND = (5, 150, 105)    # emerald-600
_DARK = (6, 95, 70)       # emerald-900
_MUTED = (100, 116, 139)
_ZEBRA = (236, 253, 245)  # emerald-50


def _ps(value) -> str:
    """latin-1 safe text for fpdf2 core fonts."""
    return str(value).encode("latin-1", "replace").decode("latin-1")


def rota_to_pdf(shifts: list[dict], hotel_name: str, date_from, date_to) -> bytes:
    """A clean, branded server-side rota PDF (not a browser screen-print)."""
    pdf = FPDF()
    pdf.add_page()
    # Brand header band
    pdf.set_fill_color(*_BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 8)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_ps(hotel_name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0, 6, text=_ps(f"ROTA   |   {date_from}  to  {date_to}"),
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    # Table header
    pdf.set_xy(14, 40)
    pdf.set_fill_color(*_DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(64, 9, text="  Employee", fill=True)
    pdf.cell(34, 9, text="Date", align="C", fill=True)
    pdf.cell(28, 9, text="Start", align="C", fill=True)
    pdf.cell(28, 9, text="End", align="C", fill=True)
    pdf.cell(28, 9, text="Hours  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*_DARK)
    pdf.set_font("Helvetica", "", 10)
    total = Decimal("0")
    if not shifts:
        pdf.set_x(14)
        pdf.cell(
            0, 9, text="  No shifts scheduled for this week.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
    for i, s in enumerate(shifts):
        pdf.set_x(14)
        fill = i % 2 == 1
        pdf.set_fill_color(*_ZEBRA)
        pdf.cell(64, 8, text=f"  {_ps(s['employee_name'])}", fill=fill)
        pdf.cell(34, 8, text=_ps(str(s["date"])), align="C", fill=fill)
        pdf.cell(28, 8, text=s["start_time"].strftime("%H:%M"), align="C", fill=fill)
        pdf.cell(28, 8, text=s["end_time"].strftime("%H:%M"), align="C", fill=fill)
        pdf.cell(
            28, 8, text=f"{s['hours']}  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        total += s["hours"]

    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(*_ZEBRA)
    pdf.cell(154, 9, text="  Total hours", fill=True)
    pdf.cell(28, 9, text=f"{total}  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*_MUTED)
    pdf.set_y(285)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, text="Generated by Mise - every plate, every penny", align="C")
    return bytes(pdf.output())


def rota_to_xlsx(shifts: list[dict], date_from: date_type, date_to: date_type) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Rota"
    headers = ["Employee", "Date", "Start", "End", "Hours", "Notes"]
    r = 4
    total = Decimal("0")
    for s in shifts:
        ws.cell(row=r, column=1, value=s["employee_name"])
        ws.cell(row=r, column=2, value=str(s["date"]))
        ws.cell(row=r, column=3, value=s["start_time"].strftime("%H:%M"))
        ws.cell(row=r, column=4, value=s["end_time"].strftime("%H:%M"))
        ws.cell(row=r, column=5, value=float(s["hours"]))
        ws.cell(row=r, column=6, value=s.get("notes") or "")
        total += s["hours"]
        r += 1
    style_table(
        ws, title="Mise — Rota", subtitle=f"{date_from} → {date_to}", headers=headers,
        n_rows=len(shifts), widths=[26, 14, 10, 10, 10, 30], right_cols={5},
    )
    total_row(ws, row=r + 1, label="Total hours", label_col=4, value=float(total), value_col=5)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def template_xlsx(employee_names: list[str]) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Rota"
    headers = ["Employee", "Date", "Start", "End", "Notes"]
    ws.cell(row=4, column=1, value=employee_names[0] if employee_names else "Staff full name")
    ws.cell(row=4, column=2, value="2026-06-30")
    ws.cell(row=4, column=3, value="09:00")
    ws.cell(row=4, column=4, value="17:00")
    ws.cell(row=4, column=5, value="(optional)")
    style_table(
        ws, title="Mise — Rota template", headers=headers, n_rows=1,
        subtitle="Fill a row per shift, then upload on the Rota page",
        widths=[26, 14, 10, 10, 30],
    )
    if employee_names:
        ws2 = wb.create_sheet("Employees")
        note = "Use these exact names in the Employee column:"
        ws2.cell(row=1, column=1, value=note).font = Font(bold=True)
        for i, n in enumerate(employee_names, start=2):
            ws2.cell(row=i, column=1, value=n)
        ws2.column_dimensions["A"].width = 28
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _parse_date(v) -> date_type | None:
    if isinstance(v, datetime):
        return v.date()
    if isinstance(v, date_type):
        return v
    s = str(v or "").strip()[:10]
    try:
        return date_type.fromisoformat(s)
    except ValueError:
        return None


def _parse_time(v) -> time | None:
    if isinstance(v, datetime):
        return v.time()
    if isinstance(v, time):
        return v
    s = str(v or "").strip()
    for fmt in ("%H:%M", "%H:%M:%S", "%I:%M %p", "%I:%M%p", "%I%p"):
        try:
            return datetime.strptime(s.upper(), fmt).time()
        except ValueError:
            continue
    return None


def parse_rota_xlsx(file_bytes: bytes, max_rows: int = 500) -> list[dict]:
    """Filled template → [{employee_name, date, start_time, end_time, notes}]. Rows
    missing a name/date/start/end are skipped. Best-effort; bad files → []."""
    try:
        wb = load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
        ws = wb.active
        rows = list(ws.iter_rows(values_only=True))
    except Exception:  # noqa: BLE001 — unreadable file → nothing parsed
        return []

    start_idx = 0
    for i, row in enumerate(rows[:5]):
        if row and any(str(c or "").strip().lower() == "employee" for c in row):
            start_idx = i + 1
            break

    out: list[dict] = []
    for row in rows[start_idx:start_idx + max_rows]:
        if not row:
            continue
        name = str(row[0]).strip() if len(row) > 0 and row[0] else ""
        if not name:
            continue
        d = _parse_date(row[1]) if len(row) > 1 else None
        st = _parse_time(row[2]) if len(row) > 2 else None
        en = _parse_time(row[3]) if len(row) > 3 else None
        if not (d and st and en):
            continue
        notes = str(row[4]).strip() if len(row) > 4 and row[4] else None
        out.append({
            "employee_name": name, "date": d, "start_time": st, "end_time": en, "notes": notes,
        })
    return out
