"""Daily attendance timesheet exports — branded PDF + Excel (openpyxl)."""
import io

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from openpyxl import Workbook
from openpyxl.styles import Font

BRAND = (16, 185, 129)
DARK = (15, 23, 42)
MUTED = (100, 116, 139)
LIGHT = (241, 245, 249)


def _s(value) -> str:
    return str(value).encode("latin-1", "replace").decode("latin-1")


def _hm(dt) -> str:
    return dt.strftime("%H:%M") if dt else "-"


def _cols(row: dict) -> tuple[str, str, str, str, str]:
    return (
        _s(row["employee_name"]),
        _hm(row.get("clock_in")),
        _hm(row.get("clock_out")),
        str(row.get("working_hours") or "-"),
        str(row.get("status") or "-"),
    )


def generate_timesheet_pdf(rows: list[dict], hotel, day) -> bytes:
    pdf = FPDF()
    pdf.add_page()

    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 9)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_s(hotel.name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, text=f"ATTENDANCE TIMESHEET   |   {day}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_xy(14, 40)
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(74, 9, text="  Employee", fill=True)
    pdf.cell(28, 9, text="In", align="C", fill=True)
    pdf.cell(28, 9, text="Out", align="C", fill=True)
    pdf.cell(28, 9, text="Hours", align="R", fill=True)
    pdf.cell(24, 9, text="Status  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "", 10)
    if not rows:
        pdf.set_x(14)
        pdf.cell(
            0, 9, text="  No attendance recorded for this day.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
    for i, r in enumerate(rows):
        name, cin, cout, hours, status = _cols(r)
        pdf.set_x(14)
        fill = i % 2 == 1
        pdf.set_fill_color(*LIGHT)
        pdf.cell(74, 8, text=f"  {name}", fill=fill)
        pdf.cell(28, 8, text=cin, align="C", fill=fill)
        pdf.cell(28, 8, text=cout, align="C", fill=fill)
        pdf.cell(28, 8, text=hours, align="R", fill=fill)
        pdf.cell(
            24, 8, text=f"{status}  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    pdf.set_text_color(*MUTED)
    pdf.set_xy(14, 280)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5, text="Generated by Mise - restaurant intelligence",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    return bytes(pdf.output())


def generate_timesheet_xlsx(rows: list[dict], hotel, day) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Timesheet"
    title = ws.cell(row=1, column=1, value=f"{hotel.name} — Attendance {day}")
    title.font = Font(bold=True, size=14)
    headers = ["Employee", "Clock in", "Clock out", "Hours", "Status"]
    for col, h in enumerate(headers, start=1):
        ws.cell(row=3, column=col, value=h).font = Font(bold=True)
    r = 4
    for row in rows:
        name, cin, cout, hours, status = _cols(row)
        ws.cell(row=r, column=1, value=row["employee_name"])
        ws.cell(row=r, column=2, value=cin)
        ws.cell(row=r, column=3, value=cout)
        ws.cell(row=r, column=4, value=str(row.get("working_hours") or ""))
        ws.cell(row=r, column=5, value=status)
        r += 1
    ws.column_dimensions["A"].width = 28
    for c in ("B", "C", "D", "E"):
        ws.column_dimensions[c].width = 14
    bio = io.BytesIO()
    wb.save(bio)
    return bio.getvalue()
