"""Daily attendance timesheet exports — branded PDF + Excel (openpyxl)."""
import io

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from openpyxl import Workbook

from app.core.xlsx_style import style_table

BRAND = (16, 185, 129)
DARK = (15, 23, 42)
MUTED = (100, 116, 139)
LIGHT = (241, 245, 249)


def _s(value) -> str:
    return str(value).encode("latin-1", "replace").decode("latin-1")


def _hm(dt) -> str:
    return dt.strftime("%H:%M") if dt else "-"


def _cols(row: dict) -> tuple[str, str, str, str, str]:
    return (
        _s(row["employee_name"]),
        _hm(row.get("clock_in")),
        _hm(row.get("clock_out")),
        str(row.get("working_hours") or "-"),
        str(row.get("status") or "-"),
    )


def generate_timesheet_pdf(rows: list[dict], hotel, day) -> bytes:
    pdf = FPDF()
    pdf.add_page()

    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 9)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 9, text=_s(hotel.name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, text=f"ATTENDANCE TIMESHEET   |   {day}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_xy(14, 40)
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(74, 9, text="  Employee", fill=True)
    pdf.cell(28, 9, text="In", align="C", fill=True)
    pdf.cell(28, 9, text="Out", align="C", fill=True)
    pdf.cell(28, 9, text="Hours", align="R", fill=True)
    pdf.cell(24, 9, text="Status  ", align="R", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "", 10)
    if not rows:
        pdf.set_x(14)
        pdf.cell(
            0, 9, text="  No attendance recorded for this day.",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
    for i, r in enumerate(rows):
        name, cin, cout, hours, status = _cols(r)
        pdf.set_x(14)
        fill = i % 2 == 1
        pdf.set_fill_color(*LIGHT)
        pdf.cell(74, 8, text=f"  {name}", fill=fill)
        pdf.cell(28, 8, text=cin, align="C", fill=fill)
        pdf.cell(28, 8, text=cout, align="C", fill=fill)
        pdf.cell(28, 8, text=hours, align="R", fill=fill)
        pdf.cell(
            24, 8, text=f"{status}  ", align="R", fill=fill,
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

    pdf.set_text_color(*MUTED)
    pdf.set_xy(14, 280)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 5, text="Generated by Mise - restaurant intelligence",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    return bytes(pdf.output())


def generate_timesheet_xlsx(rows: list[dict], hotel, day) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Timesheet"
    r = 4
    for row in rows:
        name, cin, cout, hours, status = _cols(row)
        ws.cell(row=r, column=1, value=row["employee_name"])
        ws.cell(row=r, column=2, value=cin)
        ws.cell(row=r, column=3, value=cout)
        ws.cell(row=r, column=4, value=str(row.get("working_hours") or ""))
        ws.cell(row=r, column=5, value=status)
        r += 1
    style_table(
        ws, title=f"{hotel.name} — Attendance", subtitle=str(day),
        headers=["Employee", "Clock in", "Clock out", "Hours", "Status"],
        n_rows=len(rows), widths=[28, 14, 14, 12, 14], right_cols={4},
    )
    bio = io.BytesIO()
    wb.save(bio)
    return bio.getvalue()


def generate_range_xlsx(rows: list[dict], hotel, date_from, date_to) -> bytes:
    """Any-range export: one row per person per day, plus a per-person totals tab.

    style_table owns the title/header rows (data starts at row 4), so we write
    cells from r=4 down — matching generate_timesheet_xlsx."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Attendance"
    totals: dict[str, dict] = {}
    r = 4
    for row in rows:
        ws.cell(row=r, column=1, value=str(row.get("date", "")))
        ws.cell(row=r, column=2, value=row.get("employee_name", ""))
        ws.cell(row=r, column=3, value=row.get("status", ""))
        ws.cell(row=r, column=4, value=_hm(row.get("clock_in")))
        ws.cell(row=r, column=5, value=_hm(row.get("clock_out")))
        ws.cell(row=r, column=6, value=row.get("break_minutes") or 0)
        ws.cell(row=r, column=7, value=float(row.get("working_hours") or 0))
        t = totals.setdefault(row.get("employee_name", "?"), {"days": 0, "hours": 0.0})
        t["days"] += 1
        t["hours"] += float(row.get("working_hours") or 0)
        r += 1
    style_table(
        ws, title=f"{hotel.name} — Attendance", subtitle=f"{date_from} to {date_to}",
        headers=["Date", "Employee", "Status", "In", "Out", "Break (min)", "Hours"],
        n_rows=len(rows), widths=[13, 24, 12, 10, 10, 12, 10], right_cols={6, 7},
    )
    ws2 = wb.create_sheet("Totals by person")
    r2 = 4
    for name, t in sorted(totals.items()):
        ws2.cell(row=r2, column=1, value=name)
        ws2.cell(row=r2, column=2, value=t["days"])
        ws2.cell(row=r2, column=3, value=round(t["hours"], 2))
        r2 += 1
    style_table(
        ws2, title="Totals by person", subtitle=f"{date_from} to {date_to}",
        headers=["Employee", "Recorded days", "Total hours"],
        n_rows=len(totals), widths=[28, 16, 14], right_cols={2, 3},
    )
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
