"""sales: channels, daily_sales, sales_lines

Revision ID: 49f503832642
Revises: 0005
Create Date: 2026-06-07 12:42:39.907709
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '49f503832642'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'name', name='uq_channel_hotel_name')
    )
    op.create_index(op.f('ix_sales_channels_hotel_id'), 'sales_channels', ['hotel_id'], unique=False)
    op.create_table('daily_sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_counted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'date', name='uq_dailysales_hotel_date')
    )
    op.create_index(op.f('ix_daily_sales_hotel_id'), 'daily_sales', ['hotel_id'], unique=False)
    op.create_table('sales_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('daily_sales_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['sales_channels.id'], ),
    sa.ForeignKeyConstraint(['daily_sales_id'], ['daily_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_lines_daily_sales_id'), 'sales_lines', ['daily_sales_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_lines_daily_sales_id'), table_name='sales_lines')
    op.drop_table('sales_lines')
    op.drop_index(op.f('ix_daily_sales_hotel_id'), table_name='daily_sales')
    op.drop_table('daily_sales')
    op.drop_index(op.f('ix_sales_channels_hotel_id'), table_name='sales_channels')
    op.drop_table('sales_channels')
    # ### end Alembic commands ###
