"""vendors: vendors and vendor_items

Revision ID: 54a089e72c96
Revises: 25c10b28b530
Create Date: 2026-06-06 21:57:40.346941
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54a089e72c96'
down_revision: str | None = '25c10b28b530'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vat_number', sa.String(length=40), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('bank_account_no', sa.String(length=20), nullable=True),
    sa.Column('bank_sort_code', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('vendor_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'item_id', name='uq_vendor_item')
    )
    op.create_index(op.f('ix_vendor_items_item_id'), 'vendor_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_vendor_items_vendor_id'), 'vendor_items', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_items_vendor_id'), table_name='vendor_items')
    op.drop_index(op.f('ix_vendor_items_item_id'), table_name='vendor_items')
    op.drop_table('vendor_items')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
