"""documents

Revision ID: e3bdff467d96
Revises: f3381f77e02a
Create Date: 2026-06-07 18:03:49.760619
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3bdff467d96'
down_revision: str | None = 'f3381f77e02a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hotel_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('related_entity_type', sa.String(length=20), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_hotel_id'), 'documents', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_hotel_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
