import { test } from "@playwright/test";
const BASE = "https://nirai1.dineai.cloud";
test("what is clipped in the popup", async ({ page }) => {
  await page.goto(`${BASE}/login`);
  await page.locator("#li-email:visible").first().fill("superadmin@gmail.com");
  await page.locator("#li-password:visible").first().fill("superadmin@123");
  await page.getByRole("button", { name: "Sign in" }).filter({ visible: true }).first().click();
  await page.waitForURL("**/dashboard", { timeout: 60_000 });
  await page.evaluate(() => localStorage.setItem("mise.tour.done", "1"));
  await page.setViewportSize({ width: 1536, height: 730 });
  await page.goto(`${BASE}/staff`);
  await page.getByRole("button", { name: /create a role/i }).click();
  await page.getByText(/^No access$/).first().waitFor({ timeout: 60_000 });
  await page.waitForTimeout(1200);
  const out = await page.evaluate(() => {
    const dlg = document.querySelectorAll('[role="dialog"]');
    const panel = dlg[dlg.length - 1].querySelector(".mise-pop-lg") as HTMLElement;
    const r: string[] = [];
    const pr = panel.getBoundingClientRect();
    r.push(`panel top=${Math.round(pr.top)} bottom=${Math.round(pr.bottom)} h=${Math.round(pr.height)} vh=${window.innerHeight}`);
    [...panel.children].forEach((c, i) => {
      const e = c as HTMLElement;
      const b = e.getBoundingClientRect();
      r.push(`child${i} ${e.tagName} h=${Math.round(b.height)} top=${Math.round(b.top)} bot=${Math.round(b.bottom)}`);
    });
    const nav = panel.querySelector("nav") as HTMLElement;
    r.push(`nav sh=${nav.scrollHeight} ch=${nav.clientHeight} bot=${Math.round(nav.getBoundingClientRect().bottom)}`);
    const items = nav.querySelectorAll("button");
    const last = items[items.length - 1].getBoundingClientRect();
    r.push(`lastRail bot=${Math.round(last.bottom)}`);
    const detail = nav.nextElementSibling as HTMLElement;
    r.push(`detail sh=${detail.scrollHeight} ch=${detail.clientHeight}`);
    const cards = detail.querySelectorAll("li");
    const lc = cards[cards.length - 1].getBoundingClientRect();
    r.push(`lastCard bot=${Math.round(lc.bottom)}`);
    const foot = panel.querySelector("footer") as HTMLElement;
    r.push(`footer top=${Math.round(foot.getBoundingClientRect().top)}`);
    return r;
  });
  console.log("DIAG:" + out.join(" || "));
});
