"""Shared branded PDF helpers (fpdf2) so every Mise PDF download has the same calm,
professional emerald look: an emerald header band, a coloured table header, zebra
rows and a footer. Import branded_pdf()/footer() and lay your content beneath."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos

BRAND = (5, 150, 105)    # emerald-600
DARK = (6, 95, 70)       # emerald-900
MUTED = (100, 116, 139)  # slate-500
ZEBRA = (236, 253, 245)  # emerald-50
TOTAL = (209, 250, 229)  # emerald-100


def ps(value) -> str:
    """latin-1 safe text for fpdf2 core fonts (replaces unsupported glyphs)."""
    return str(value).encode("latin-1", "replace").decode("latin-1")


def branded_pdf(title: str, subtitle: str = "", orientation: str = "P") -> FPDF:
    """A fresh page with the emerald header band (title + optional subtitle) drawn and
    the cursor left just below it, ready for content. Auto page-break is on."""
    pdf = FPDF(orientation=orientation)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, pdf.w, 28, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 7)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 9, text=ps(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if subtitle:
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 6, text=ps(subtitle), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_xy(14, 34)
    pdf.set_text_color(*DARK)
    return pdf


def table_header(pdf: FPDF, cols: list[tuple[str, float, str]], height: float = 9) -> None:
    """Draw an emerald header row. cols = [(label, width, align), …]; align in L/C/R."""
    pdf.set_x(14)
    pdf.set_fill_color(*DARK)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    for i, (label, w, align) in enumerate(cols):
        last = i == len(cols) - 1
        pdf.cell(
            w, height, text=ps(label), align=align, fill=True,
            new_x=XPos.LMARGIN if last else XPos.RIGHT,
            new_y=YPos.NEXT if last else YPos.TOP,
        )
    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "", 9)


def footer(pdf: FPDF, text: str = "Generated by Mise - every plate, every penny") -> None:
    pdf.set_text_color(*MUTED)
    pdf.set_y(pdf.h - 12)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, text=ps(text), align="C")
